module.exports = ({
    Janani: 'ஜனனி',
    WELCOME: 'வரவேற்பு',
    Settings: 'அமைப்புகள்',
    Logout: 'வெளியேறு',
    Import_from_PICME: 'PICME இருந்து இறக்குமதி',
    Name: 'பெயர்',
    Age: 'வயது',
    ContactNo: 'தொடர்பு எண்',
    Spouse: 'மனைவி',
    Obsterics: 'Obsterics',
    Risk: 'இடர்',
    BloodGroup: 'இரத்த வகை',
    PICMEID: 'PICME ஐடி',
    JananiID: 'ஜனனி ஐடி',
    PregnencyStatus: 'கர்ப்பம் நிலைமை',
    BP: 'இரத்த அழுத்தம்',
    DateofLMP:'LMP தேதி',
    ExpectedDateOfDelivery:'Ex தேதி',
    PatientID: 'நோயாளி ஐடி',
    SubCenterName: 'துணை மையம் பெயர்',
    ReferredTo: 'குறிப்பிடப்படுகிறது:',
    RefferedOn: 'குறிப்பிட்டிருக்கிறார்:',
    ReasonForReferral: 'குறிப்பு காரணம்:',
    ModeOfTransport: 'போக்குவரத்து முறை:',
    Information_on_Referral_provided_to_institution_referred: 'நிறுவனத்திற்கு வழங்கப்பட்ட பரிந்துரை பற்றிய தகவல் குறிப்பிட்டார்:',
    CurrentMedication: 'தற்போதைய மருந்து:',
    PatientConsentObtained: 'நோயாளி ஒப்புதல் பெற்றதாகவும்:',
    Print_Export_to_PDF: 'அச்சு (PDF ஆக ஏற்றுமதி)',
    Cancel: 'ரத்து',
    PleaseEenter: 'உள்ளிடவும்',
    PleaseEnterTheReason: 'காரணத்தை உள்ளிடவும்',
    PHCName: 'PHC பெயர்',
    Yes: 'ஆம்',
    No: 'இல்லை',
    SpouseName: 'கணவன் அல்லது மனைவியின் பெயர்',
    PATIENTINFORMATION: 'நோயாளி தகவல்'
});