module.exports = ({
    Janani: 'Janani',
    WELCOME: 'WELCOME',
    Settings: 'Settings',
    Logout: 'Logout',
    Import_from_PICME: 'Import from PICME',
    ContactNo: 'Contact No',
    Spouse: 'Spouse',
    Obsterics: 'Obsterics',
    Risk: 'Risk',
    BloodGroup: 'Blood Group',
    isHighRisk: 'Is High Risk Mother',
    PregnencyStatus: 'Pregnency Status',
    Save: 'Save',
    Submit: 'Submit',
    Discard: 'Discard',
    Import: 'Import',
    cancel: 'Cancel',
    Yes: 'Yes',
    No: 'No',
    CurrentPregnancy: 'Current Pregnancy',
    CurrentPregnancyTitle: 'This section records Current Pregnancy information',
    PregnancyAcceptedWillingly: 'If pregnancy is wanted?',
    DateofLMP: 'LMP',
    ExpectedDateOfDelivery: 'EDD by Date',
    EDDByUSG: 'EDD by USG',    
    MandatoryField: 'Mandatory field',
    HistOfCurrentIllness: 'History of Current Illness',
    HistOfCurrentIllnessTitle: 'This section records History of Current Illness information',
    Nausea: 'Nausea',
    Vomiting: 'Vomiting',
    Heartburn: 'Heartburn',
    Constipation: 'Constipation',
    IncreasedFrequencyOfUrination: 'Increased frequency of urination',
    Fever: 'Fever',
    PersistentVomiting: 'Persistent vomiting',
    AbnormalVaginalDischargeOrItching: 'Abnormal vaginal discharge/itching',
    PalpitationsEasyFatigability: 'Palpitations, easy fatigability',
    BreathlessnessAtRestOnMildExertion: 'Breathlessness at rest/on mild exertion',
    GenSwellingOfTheBodyPuffinessOfTheFace: 'Generalised swelling of the body, puffiness of the face',
    SevereHeadacheAndBlurringOfVision: 'Severe headache and blurring of vision',
    BurningSensationDuringMicturition: 'Passing smaller amounts of urine and burning sensation during micturition',
    VaginalBleeding: 'Vaginal bleeding',
    LeakingOfWateryFluidPerVaginum: 'Leaking of watery fluid per vaginum (P/V)',
    AbdominalExamination: 'Abdominal Examination',
    AbdominalExaminationTitle: 'This section records Abdominal Examination information',
    Longitudinal: 'Longitudinal',
    Transverse: 'Transverse',
    Oblique: 'Oblique',
    Cephalic: 'Cephalic',
    Breech: 'Breech',
    Shoulder: 'Shoulder',
    Single: 'Single',
    Multiple: 'Multiple',
    InspectationOfScarsOrAbdominalFindings: 'Inspectation of any scars or other relevent abdominal findings',
    FundalHeightInCM: 'Fundal Height in cms',
    FundalHeight: 'Fundal Height in weeks',
    FoetalLie: 'Foetal Lie',
    FoetalPresentation: 'Foetal presentation',
    FHS: 'FHS (Foetal heart Rate)',
    SingleVsMultiplePregnancy: 'Single Vs Multiple Pregnancy',
    FoetalMovements: 'Foetal Movements',
    Allergies: 'Allergies',
    AllergiesTitle: 'This section records General Examination information',
    DrugAllergies: 'Drug Allergies',
    FoodAllergies: 'Food Allergies',
    EnviornmentalAllergies: 'Enviornmental Allergies',
    BreastExamination: 'Breast Examination',
    BreastExaminationTitle: 'This section records Breast Examination information',
    LeftBreast: 'Left Breast',
    RightBreast: 'Right Breast',
    Normal: 'Normal',
    RetractedNipple: 'Retracted nipple',
    Nodule: 'Nodule',
    Lump: 'Lump',
    Scar: 'Scar',
    FamilyHistory: 'Family History',
    FamilyHistoryTitle: 'This section records Family History information',
    HighBP: 'High blood pressure (hypertension)',
    Diabetes: 'Diabetes',
    Tuberculosis: 'Tuberculosis',
    TwinsInImmediateFamily: 'Twins in immediate Family',
    CongeniatlMalfomationsInImmediateFamily: 'Congeniatl Malfomations in immediate family',
    GeneralExamination: 'General Examination',
    GeneralExaminationTitle: 'This section records General Examination information',
    HeightIncms: 'Height in cms',
    WeightInKgs: 'Weight in Kgs',
    Pallor: 'Pallor',
    Jaundice: 'Jaundice',
    Pulse: 'Pulse',
    RespiratoryRatePM: 'Respiratory Rate per min',
    Oedema: 'Oedema',
    BP: 'Blood Pressure',
    TemperatureInFarenheit: 'Temperature in farenheit',
    TooWeakToGetOutOfBed: 'Too weak to get out of bed',
    HabbitsAndSocialHistory: 'Habbits and Social History',
    HabbitsAndSocialHistoryTitle: 'This section records Habbits and Social History information',
    Tobacco: 'Tobacco',
    Smoking: 'Smoking',
    Drugs: 'Drugs',
    Alcohol: 'Alcohol',
    MenstrualHistory: 'Menstrual History',
    MenstrualHistoryTitle: 'This section records Menstrual History information',
    Regularity: 'Regularity',
    Regular: 'Regular',
    Irregular: 'Irregular',
    FrequencyInNumberOfDays: 'Frequency in number of days',
    NumberOfDaysOfBleed: 'Number of days of bleed',
    AgeAtMenarche: 'Age at Menarche',
    PainAssociatedWithPeriods: 'Pain associated with Periods',
    ObstetricHistory: 'Obstetric History',
    ObstetricHistoryTitle: 'This section records Obstetric History information',
    Gravida: 'Gravida',
    Para: 'Para',
    LiveBirths: 'Live Births',
    RecurrentEarlyAbortion: 'Recurrent early abortion',
    PostAbortionComplications: 'Post-abortion Complications',
    HypertensionPreEclmpsiaOrEclampsia: 'Hypertension,Pre-eclmpsia or eclampsia',
    AntePartumHaemorrhage: 'Ante-Partum Haemorrhage (APH)',
    BreechOrTransversePresentation: 'Breech or transverse presentation',
    obstructedLabourIncludingDystocia: 'Obstructed labour,including dystocia',
    PerinealInjuriesTears: 'Perineal injuries/tears',
    ExcessiveBleedingAfterDelivery: 'Excessive bleeding after delivery',
    PuerperalSepsis: 'Puerperal sepsis',
    BloodTransfusionDuringPrevPregnancies: 'Blood Transfusion during previous Pregnancies',
    StillbirthOrNeonatalLoss: 'Stillbirth or neonatal loss',
    MoreConsecutiveAbortions: 'Three or more spontaneous consecutive abortions',
    ObstructedLabour: 'Obstructed labour',
    PrematureBirthsTwinsOrMultiplePregnancies: 'Premature births, twins or multiple pregnancies',
    PrevBaby4500gOrMore: 'Weight of the previous baby 4500 g or more',
    Adm4HTOrPreEclampsiaEclampsiaInPrevpregnancy: 'Admission for hypertension or pre-eclampsia/eclampsia in the previous pregnancy',
    SurgeryOnTheReproductiveTract: 'Surgery on the reproductive tract',
    CongenitalAnomaly: 'Congenital anomaly',
    Treatment4Infertility: 'Treatment for infertility',
    SpinalDeformities: 'Spinal deformities, such as scoliosis/kyphosis/polio',
    RhNegInThePrevPregnancy: 'Rh negative in the previous pregnancy',
    PastMedicalHistory: 'Past Medical History',
    PastMedicalHistoryTitle: 'This section records past Medical History information',
    BloodPressure: 'Blood pressure',
    HighBloodPressure_hypertension: 'High blood pressure',
    OnMedication: 'On medication?',
    Diabetes_Types: 'Type1, Type 2',
    Breathlessness: 'Breathlessness',
    Breathlessness_on_exertion_palpitations_HeartDisease: 'On exertion, palpitations (heart disease)',
    RenalDisease: 'Renal disease',
    RenalDisease_KidneyFailure: 'Kidney failure?',
    Convulsions : 'Convulsions',
    Convulsions_Types: 'Epilepsy , Histerias etc',
    Asthama : 'Asthama',
    Attacksofbreathlessness_asthma: 'Attacks of breathlessness	or asthma',
    Jaundice_Types: 'Pre-hepatic, hepatic, post?',
    Malaria: 'Malaria',
    Malariasymptoms: 'Any symptoms?',
    RTI: 'RTI',
    ReproductiveTractInfection_RTI: 'Reproductive Tract Infection',
    STI_AIDS: 'STI/AIDS',
    SexuallyTransmittedInfection_STI_and_HIV_AIDS: 'Sexually Transmitted Infection and HIV/AIDS',
    SystemicExamination: 'Systemic Examination',
    SystemicExaminationTitle: 'This section records Systemic Examination information',
    NormCardiovasculary: 'Normal Cardiovasculary System',
    NormNervous: 'Normal Nervous System',
    NormDigestive: 'Normal Digestive System',
    NormMusculoskeltal: 'Normal Musculoskeltal System',
    MedicalHistory: 'Medical History',
    MedicalHistoryTitle: 'This section records Medical History',
    PhysicalExamination: 'Physical Examination',
    PhysicalExaminationTitle: 'This section records Physical Examination information',
    LabResultsandOrders: 'Lab Results and Orders',
    LabResultsandOrdersTitle: 'This section records Lab Results and Orders information',
    Orders: 'Orders',
    Results: 'Results',
    BloodGroup_including_RhFactor: 'Blood group, including Rh factor',
    VDRL_RPR: 'VDRL/RPR',
    HIV_testing: 'HIV testing',
    Rapid_Malaria_Test: 'Rapid malaria test (if unavailable at SC)',
    BloodSugar: 'Blood Sugar',
    HbsAg: 'HbsAg',
    CBC_with_ESR: 'CBC with ESR',
    PeripheralSmear: 'Peripheral Smear',
    UPT: 'UPT',
    Hb: 'Hb',
    UrineSugar: 'Urine Sugar',
    UrineProteins: 'Urine Proteins',
    RapidMalariaTest: 'Rapid Malaria Test',
    Positive: 'Positive',
    Negative: 'Negative',
    AddressLine1: 'Address',
    AddressLine2: 'Address 2',
    AddressLine3: 'Address 3',
    EnterAddLine1: 'Enter Address',
    EnterAddLine2: 'Enter Address 2',
    EnterAddLine3: 'Enter Address 3',
    Village: 'Village',
    SelVill: 'Select Village',
    City: 'City',
    SelCity: 'Select City',
    State: 'State',
    SelState: 'Select State',
    Pincode: 'Pincode',
    EnterPIN: 'Enter Pincode',
    TempAddressSame: 'Temporary address same as permanent',
    Sub_Center_ID:'Sub-Center ID',
    Sub_Center_Name:'Sub-Center Name',
    VHN_Name:'VHN Name',
    Name: 'Name',
    EnterName: 'Enter Name',
    DOB: 'Date of Birth',
    ECN: 'Emergency Contact Number',
    EnterECN: 'Enter Emergency Contact Number',
    SpouseName: 'Spouse Name',
    EnterSpouseName: 'Enter Spouse Name',
    Age: 'Age',
    JananiID: 'Janani ID',
    NextVisitDate: 'Next Visit Date',
    PICMEID: 'PICME ID',
    EnterPICMEID: 'Enter PICME ID',
    MedicalPrescriptions: 'Medical prescriptions',
    MedicalPrescriptionsTitle: 'This section records Medical prescriptions information',
    Inj_TT_IM: 'Inj. TT 0.5ml IM',
    FolicAcidSuppliment_IFA: 'Folic Acid Suppliment (IFA)',
    Counselling: 'Counselling - Diet, Importance of ANC, domestic violence, sex during Pregnancy',
    Issue_MaternalChildProtectionCard: 'Issue Maternal & Child Protection Card',
    JSYCard: 'JSY Card',
    BPLCard: 'BPL Card',
    RecordPossibleLocationOfDelivery: 'Record Possible Location of Delivery',
    PHCName: 'PHC Name',
    PrimaryInformation: 'Primary Information',
    PrimaryInformationTitle: 'This section records Mother Genearal information',
    MothersDemographicInformation: 'Mother\'s Demographic Information',
    MothersDemographicInformationTitle: 'This section records Mothers Demographics information',
    Comments: 'Comments',
    GeneralComments: 'General comments if any',
    IncidentCapture: 'Incident capture',
    Prescriptions_photos_scans_Allergies: 'Prescriptions , photos , Scans , Allergies etc',
    Attachements: 'Attachements if any',
    Upload: 'Upload',
    ClickToTakePhotosOrVideos: 'Click to take photos or videos',
    PregnancyHistory : 'Pregnancy History',
    Pregnancies : 'Pregnancies',
    Abortions : 'Abortions',
    VisitInformation : 'Visit Information',
    BasicInformation : 'Basic Information',
    PastEpisodes : 'Past Episodes',
    ReportsAndResults : 'Reports and Results',
    RiskProfile : 'Risk Profile',
    AddPatient : 'Add Patient',
    PatientID: 'Patient ID',
    SubCenterName: 'Sub Center Name',
    ReferredTo: 'Referred To:',
    RefferedOn: 'Reffered on:',
    ReasonForReferral: 'Reason For Referral:',
    ModeOfTransport: 'Mode of Transport:',
    Information_on_Referral_provided_to_institution_referred: 'Information on Referral provided to institution referred:',
    CurrentMedication: 'Current Medication:',
    PatientConsentObtained: 'Patient Consent Obtained:',
    Print_Export_to_PDF: 'Print (Export to PDF)',
    Cancel: 'Cancel',
    PleaseEenter: 'Please enter',
    PleaseEnterTheReason: 'Please enter the reason',
    PATIENTINFORMATION: 'PATIENT INFORMATION'

});