const fakeData = [{
    patientId: 'pat123',
    firstName: 'Jinal',
    middleName: 'N',
    lastName: 'Gala',
    dOB: '21/03/1987',
    isCheckDOB: 'true',
    maritalStatus: 'Single',
    isHighRiskMother: 'true',
    age: '28',
    isHighRiskGeographicMother: 'true',
    isHighRiskPhysicalStatureMother: 'true',
    isHighRiskMedicalConditionMother: 'true',
    isHighRiskSocialHistoryMother: 'true',
    addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
    district: 'Thane',
    taluka: 'Vasai',
    village: 'Virar',
    postalCode: '401303',
    state: 'Maharashtra',
    isPermanentddress: 'true',
    isDeliveryddress: 'true',
    emergencyContactRel: 'Husband',
    emergencyContactName: 'Shivakumar',
    emergencyContactAddr: 'Same As Above',
    emergencyContactPhn: '99870123456',
    lastMPDate: '16/11/2015',
    isUrinaryPT: 'true',
    urinaryPTDate: '12/10/2015',
    pregnancyCount: '2',
    bloodGroup: 'B+',
    height: '5',
    spouseName: 'Shivakumar',
    phoneNumber: '8989988989',
    obstetrics: 'G1P0A0L0',
    nextVisitDate: '19/11/2015',
    pregnancyStatus: '10'
},
    {
        patientId: 'pat114',
        firstName: 'Raji',
        middleName: 'M',
        lastName: 'Raju',
        dOB: '24/03/1988',
        isCheckDOB: 'true',
        maritalStatus: 'Single',
        isHighRiskMother: 'true',
        age: '27',
        isHighRiskGeographicMother: 'true',
        isHighRiskPhysicalStatureMother: 'true',
        isHighRiskMedicalConditionMother: 'true',
        isHighRiskSocialHistoryMother: 'true',
        addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
        district: 'Thane',
        taluka: 'Vasai',
        village: 'Virar',
        postalCode: '401303',
        state: 'Maharashtra',
        isPermanentddress: 'true',
        isDeliveryddress: 'true',
        emergencyContactRel: 'Father',
        emergencyContactName: 'Jayesh',
        emergencyContactAddr: 'Same As Above',
        emergencyContactPhn: '99870123456',
        lastMPDate: '18/11/2015',
        isUrinaryPT: 'true',
        urinaryPTDate: '12/10/2015',
        pregnancyCount: '2',
        bloodGroup: 'B+',
        height: '5',
        spouseName: 'Raju',
        phoneNumber: '9789988979',
        obstetrics: 'G1P0A0L1',
        nextVisitDate: '20/11/2015',
        pregnancyStatus: '20'
    },
    {
        patientId: 'pat115',
        firstName: 'Manju',
        middleName: 'THAKUR',
        lastName: 'Nagaraj',
        dOB: '24/03/1989',
        isCheckDOB: 'true',
        maritalStatus: 'Single',
        isHighRiskMother: 'true',
        age: '26',
        isHighRiskGeographicMother: 'true',
        isHighRiskPhysicalStatureMother: 'true',
        isHighRiskMedicalConditionMother: 'true',
        isHighRiskSocialHistoryMother: 'true',
        addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
        district: 'Thane',
        taluka: 'Vasai',
        village: 'Virar',
        postalCode: '401303',
        state: 'Maharashtra',
        isPermanentddress: 'true',
        isDeliveryddress: 'true',
        emergencyContactRel: 'Husband',
        emergencyContactName: 'Nagaraj',
        emergencyContactAddr: 'Same As Above',
        emergencyContactPhn: '99870123456',
        lastMPDate: '19/11/2015',
        isUrinaryPT: 'true',
        urinaryPTDate: '12/10/2015',
        pregnancyCount: '2',
        bloodGroup: 'B+',
        height: '5',
        spouseName: 'Nagaraj',
        phoneNumber: '9789988979',
        obstetrics: 'G1P0A0L2',
        nextVisitDate: '20/11/2015',
        pregnancyStatus: '30'
    },
    {
        patientId: 'pat116',
        firstName: 'Nirmala',
        middleName: 'Devi',
        lastName: 'Pandiyan',
        dOB: '24/03/1989',
        isCheckDOB: 'true',
        maritalStatus: 'Single',
        isHighRiskMother: 'true',
        age: '26',
        isHighRiskGeographicMother: 'true',
        isHighRiskPhysicalStatureMother: 'true',
        isHighRiskMedicalConditionMother: 'true',
        isHighRiskSocialHistoryMother: 'true',
        addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
        district: 'Thane',
        taluka: 'Vasai',
        village: 'Virar',
        postalCode: '401303',
        state: 'Maharashtra',
        isPermanentddress: 'true',
        isDeliveryddress: 'true',
        emergencyContactRel: 'Mother',
        emergencyContactName: 'Shakunthala Devi',
        emergencyContactAddr: 'Same As Above',
        emergencyContactPhn: '99870123456',
        lastMPDate: '22/11/2015',
        isUrinaryPT: 'true',
        urinaryPTDate: '12/10/2015',
        pregnancyCount: '2',
        bloodGroup: 'O+',
        height: '5',
        spouseName: 'Pandiyan',
        phoneNumber: '9283988939',
        obstetrics: 'G1P0A0L3',
        nextVisitDate: '21/11/2015',
        pregnancyStatus: '40'
    },
    {
        patientId: 'pat117',
        firstName: 'Kumari',
        middleName: '',
        lastName: 'Sambath',
        dOB: '27/04/1989',
        isCheckDOB: 'true',
        maritalStatus: 'Single',
        isHighRiskMother: 'true',
        age: '26',
        isHighRiskGeographicMother: 'true',
        isHighRiskPhysicalStatureMother: 'true',
        isHighRiskMedicalConditionMother: 'true',
        isHighRiskSocialHistoryMother: 'true',
        addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
        district: 'Thane',
        taluka: 'Vasai',
        village: 'Virar',
        postalCode: '401303',
        state: 'Maharashtra',
        isPermanentddress: 'true',
        isDeliveryddress: 'true',
        emergencyContactRel: 'Husband',
        emergencyContactName: 'Sambath',
        emergencyContactAddr: 'Same As Above',
        emergencyContactPhn: '99870123456',
        lastMPDate: '24/11/2015',
        isUrinaryPT: 'true',
        urinaryPTDate: '12/10/2015',
        pregnancyCount: '2',
        bloodGroup: 'O+',
        height: '5',
        spouseName: 'Sambath',
        phoneNumber: '9283985939',
        obstetrics: 'G1P0A0L4',
        nextVisitDate: '22/11/2015',
        pregnancyStatus: '10'
    },
    {
        patientId: 'pat118',
        firstName: 'Sandhya',
        middleName: '',
        lastName: 'Sarath',
        dOB: '27/04/1989',
        isCheckDOB: 'true',
        maritalStatus: 'Single',
        isHighRiskMother: 'true',
        age: '23',
        isHighRiskGeographicMother: 'true',
        isHighRiskPhysicalStatureMother: 'true',
        isHighRiskMedicalConditionMother: 'true',
        isHighRiskSocialHistoryMother: 'true',
        addressLine: '201-A SAI APT THAKUR WADI VIRAR-W',
        district: 'Thane',
        taluka: 'Vasai',
        village: 'Virar',
        postalCode: '401303',
        state: 'Maharashtra',
        isPermanentddress: 'true',
        isDeliveryddress: 'true',
        emergencyContactRel: 'Husband',
        emergencyContactName: 'Sambath',
        emergencyContactAddr: 'Same As Above',
        emergencyContactPhn: '99870123456',
        lastMPDate: '26/11/2015',
        isUrinaryPT: 'true',
        urinaryPTDate: '12/10/2015',
        pregnancyCount: '2',
        bloodGroup: 'O+',
        height: '5',
        spouseName: 'Saravanan',
        phoneNumber: '7283986975',
        obstetrics: 'G1P0A0L4',
        nextVisitDate: '20/12/2015',
        pregnancyStatus: '20'
    }
];

module.exports = {fakeData: fakeData};
